---
title: "notes_metrics"
author: "Ben Best"
date: "January 25, 2015"
output: html_document
---

## Announcements

- no book for reading room
- new paper from Iris
- lab update: predictive vs. explanatory

## Metrics intro

"Metrics" is a general term we're using to describe the **landscape metrics** (specific to patches) / **spatial statistics** used to quantify spatial patterns. For the purposes of Landscape Ecology this is usually surrounded around the following ideas:

1. categorical base layer, ie landcover/landuse data
2. identification of **patches**, spatially homogenous areas for variable of interest, ie landcover or species habitat

## Data types

Data come in several formats. Taking the broadest possible approach to a quantifiable observation (ie measurement), it is either:

- a human observed event (ie observation of a species, etc)
- sensor measurement, ie change in voltage
  - remote sensing: many measurements measured from afar, usually optically (either aerial photography or satellite sensor)
  - field sensor: single measurement measured for a fixed point in space, eg temperature/moisture weather station sensor (or buoy)
  
These data can then be transformed and combined to become derived or model data, which range widely in levels of complexity. At the most basic level, most all data is slightly transformed from the original voltage reading to something interprable to the units of interest. Then data could be combined for instance from multiple bands of a satellite to form a unique product such as NDVI or Chl a, intended to indicate primary productivity for land and oceans respectively. All the way to combining many measurements to spin up a full scale climate model and project into the future -- truly modeled data.

## Landscape Metrics

### Fractals

```{r}

# a
log10(4)/log10(1)

# b
log(16)/log(4)

```



